FROM microsoft/dotnet:1.0.0-preview2-sdk

WORKDIR /app

ADD src/ /app/src/

RUN dotnet restore -v minimal src/ \
    && dotnet publish -c Release -o ./ src/Analyzer/ \
    && rm -rf src/ $HOME/.nuget/

CMD ["dotnet", "Analyzer.dll", "--rabbitmq", "rabbitmq"]