FROM microsoft/dotnet:1-sdk

WORKDIR /app

ADD src/ /app/src/

RUN dotnet restore -v minimal src/Analyzer/Analyzer.csproj \
    && dotnet publish -c Release -o /app src/Analyzer/Analyzer.csproj \
    && rm -rf src/ $HOME/.nuget/

CMD ["dotnet", "Analyzer.dll", "--rabbitmq", "rabbitmq"]